os: linux
sudo: false
dist: trusty

language: java
jdk: oraclejdk8

env:
  global:
    # GH_TOKEN
    - secure: pyp2JIxKKpzerEBJyE3QgWJGDr9yyiU4iyqmo0gPM5H1oSpYLbz4QAClyq5HwMnCvH1jVX2dwZfR2jBNNrsEK3CmIm+Aktb+Ly0sDQ0XfQBpJzgyIKQFmaDVfHcNwdtElw9aiWlSWkH+dmL2baZ91Bi8W/phnRrw9hAQOrUvTeBsqctI9RApMdyHSRLW5llHwLSubNcbcroPLV7BabJFh6yd15SPZP+vEn9KQnk0jtciaWSzMrPY2H0Cr8CaXyV/ehUI3dYWhmdWVK3qYZ3djOqRLwctYRxeHf7To2KF2cuk1vWGHqORsjqaOupUv9LqLsKRA/p/GB+UwGx4p3gzIYiWp7RKwJ4csixpAOpMyVDaRtJgXiiU+K1+2Y9CvygTw7bxIkpJsldMAaCr5ig4MfvNhzH5pbru6o6sjQEvWpM+e9CI2xAsdQzcMPqa/YgRlwkQZI2xX17e4aPEbv3W070r5rydYqvrmfNLhwP/AiaWx2mXUOFrPcMSob2YG9tALjZJvsdDGwNGD/T5Nu6WMkG1PPR4M/EIUPGdWJDzNiMH15hVb67f3mc0n7gVL64qepH7DwRuhTDnmFWwEaj2CflI6Wo9tpHZ4FWw46Eu8IubdUt6Mxm5sCMWic0G94fkvNW81MtrAjHVX4VtjuamC+wTfsN7adBBBW3l3gXbRQ0=
    # CI_DEPLOY_USERNAME
    - secure: o5LP0sArXE6EoUGq4LXfqSs+nGHhKgRPaPJHDK5K9SwPHG4Md4d5+NuF904LF5QwRybaH3Yuyqqt9egUln9Je5w5/nCXxl95Kj66LfQVAIlCESUVUjhzs/pwm669LaCA35hW2qJ0iOcP6TxoKOcwsC/ctsi7sRMQ4q687tkU43aYtVeXq/9OBTS6PwkmbU5vTGZZ4C/+40fKwUUBfHbYp41krN68h8b9nf5tgOKWudU+qDGeSu/+3dGGZ4gfogrRU/uk8h/Iwox52IptQmdr5tBN+faz0JMCCzAYTxamXry8/mzS6GRfi6ERTnamIgWiYV+DfdsJ5W4w9kB23GgAAcrhz0Q1UvHutlGRrjHtttKJxzEmjXo3VOOYlIJid/mbvUrEwHjcjrDALnq4gs0tE9BJxFphdOGx2b+8T5ZtOhbqm8sZg6IoII28NrVKrqWi0sGFaHtHb34VzHCr4LhwKl5HMyibqd5RLKS21eEYg+/Y6tnv4RBWqG9mlfx6qPsUxG1QGkES34sv+T7rz/DmliFMdCMNdInp0nU+LzxVnNDtcCgfEsoe/hXpsWz+xtjU0aQCui/s5UNJw40wtkBATzKXnFtvPyzTE1WgNrVW4kZcbd9ro6fEIs04225/GDugObYMRAZx5WVRBnLECb/H62lNLfE1TOfy6sdxYbATWq4=
    # CI_DEPLOY_PASSWORD
    - secure: o6JbL2n5q1G0KekjNJrEsqEVqO1SsQWpYtNK+OlK5UQY/7UxeSyQXzgzLQf3gTa25tg6PslvVhyqjYmylxLy8Q4pcbpateKjGXe0LjCAe9AFC8HNDyMCgUDZYEYfilKwiG5z5DruZbW1LN6OKojgyMnV1DwmbmgcWlVhry26MW9GrFE3d1l2eYpjn0LGrbObtXFXfTmJ0k1rD/LXlfby0iAm93YbilArcr+Qf5DhOIo48aMlDskrO4Lj1uRPKZ8uwPSYReDt1hovxbk8OwwxW/aO4TRHFgpUMWTnEInpVOpMGa464LyFJBnN7TRlHhdUsP6CBoW4EQdOzmZS7eriGmAzsXu2aQ0j3HkEFfKeIDgzCHcptwm/4G2hZ5EZjpPAcipG5NqCEDV3hWeiJsFTLr0Ni8sux1gOEi8eAOFR9mehLBDXpMrPdtV8WmDUEwhrlCPqHo77wVMrWN5nqqKags0edmJtsEwn+qTfsIzNS5jw7xBbHypYFSE/ZfxliUPaYWMhgOjg65HySG2E89ZXn41KLqvCrQBgx16K8mw3m2oTvVrBm/MP9MLAwfyV0lu8TtevfIJlAI6WEKojo1Cay3dIdlP15fqMpCem5uyGLp8bbDdsYN+cy2MiEXAKisqreF3NJZqqWJiJeattIjNSrYqmiCoishm4EnZhoLxjZ0M=

install:
  # Resolve all dependencies
  - mvn -B -V -q -DskipTests install

script:
  # Build and test with code coverage
  - mvn -B jacoco:prepare-agent test jacoco:report jacoco:report-aggregate

after_success:
  # Publish code coverage in CodeCov
  - bash <(curl -s https://codecov.io/bash)

  # Deploy snapshot in Maven central
  - bash .util/deploy_snapshot.sh

  # Publish Javadoc in Github
  - bash .util/publish_javadoc.sh
