os: linux
sudo: false
dist: trusty

language: java
jdk: oraclejdk8

env:
  global:
    # GH_TOKEN
    - secure: pyp2JIxKKpzerEBJyE3QgWJGDr9yyiU4iyqmo0gPM5H1oSpYLbz4QAClyq5HwMnCvH1jVX2dwZfR2jBNNrsEK3CmIm+Aktb+Ly0sDQ0XfQBpJzgyIKQFmaDVfHcNwdtElw9aiWlSWkH+dmL2baZ91Bi8W/phnRrw9hAQOrUvTeBsqctI9RApMdyHSRLW5llHwLSubNcbcroPLV7BabJFh6yd15SPZP+vEn9KQnk0jtciaWSzMrPY2H0Cr8CaXyV/ehUI3dYWhmdWVK3qYZ3djOqRLwctYRxeHf7To2KF2cuk1vWGHqORsjqaOupUv9LqLsKRA/p/GB+UwGx4p3gzIYiWp7RKwJ4csixpAOpMyVDaRtJgXiiU+K1+2Y9CvygTw7bxIkpJsldMAaCr5ig4MfvNhzH5pbru6o6sjQEvWpM+e9CI2xAsdQzcMPqa/YgRlwkQZI2xX17e4aPEbv3W070r5rydYqvrmfNLhwP/AiaWx2mXUOFrPcMSob2YG9tALjZJvsdDGwNGD/T5Nu6WMkG1PPR4M/EIUPGdWJDzNiMH15hVb67f3mc0n7gVL64qepH7DwRuhTDnmFWwEaj2CflI6Wo9tpHZ4FWw46Eu8IubdUt6Mxm5sCMWic0G94fkvNW81MtrAjHVX4VtjuamC+wTfsN7adBBBW3l3gXbRQ0=
    # CI_DEPLOY_USERNAME
    - secure: NFgCssKfuDszJbb9Nhwwa0ND7ySJoA7yhINqt1tde1bR0TZUR/JCl6hP9S91lv2znFSffS7BYBfOnNOWrcJcVbirSggMpRZv18BEvQF5xNG8kShJBo1K7edzCiRIi7S29caF8jmswz7qAvjREF6O1kMVxNRqGWTrb0aj+D67OKHjd3HhVz94LRQEfbanJp8HWaxNu3/pCG8PRa2eaGD6m9iXuMgbjPkSwdeeYhzaiNWbU5oYDj52iLjNSs1F/NMW4j9TlLQOUEd7QQUj891Lp6rICT7ek28KvnngBah1jnqvfssRGD+owbnh5GR+HRNxUh3B40T2CeJ7GEL0o9TtD+o/2dFM27KkJ9crB7L7Zgn2Ro8+8SQ0562CE4V6vofee3vrvNrIdgy2FHflHzJB3RP86pNE+hyH9McgFM1pCdmrQv5c1kfIVnwmgqY3lo/vbliHMPpaAyJxbjqGdvYPHWMD7x2CgOwtqWpuAJGAjH6G5jcXztgwB+jTka4+HfJjXqctRgtUm/EqSxUjwTfcJn7Hhr2MqIug3acmxlUMWPlXmOX6a7kEt7UTZQmgK7A1AiyvQrzR6lBAxN2N/1UwsjtyfT/3spC2iQ9SRWDE4QndUl2R66XQRKjDYzZUEwdzRdoQZW9zYsoBXt14FvNNX4/K49mnxb9q0afz36DJ+iQ=
    # CI_DEPLOY_PASSWORD
    - secure: KIC2AfZyy97cbP7TGkIRtkQyubjET0PFjqeGy1uFZtt7Y31osFVDI1e5lfmkqFt12TLvpK8mXvL3d1DtjbKMFG9xvZusOofLik0BEIJN6lOpObx4tL1ItY2oARUyep0GXxRcZ/XIGBctVaHzNqcvoEkoiZ/oBmK3XK2WZ+B1v+evtzdBtOBzg7RzFhSVBaeVkZycWhXmDciFZBY/BhLge5TZqiiK3iA+FwSItz/BQ2VfNN9jWFTHtOxvUx46LHFAKdUqM3TT4rzKCK1Of02Pwds+oTSGlupdcB5r2PZx0X6w1kjr5qLmcQu0mn7W2S+RLHY8TlgNFJVRENfaLUFUCfiXjed1ukC1WfGAbrnlDowgAXsqnYN+pRN00VvjMH96NczSFGv8JX0jvTYyE39UvHEt5Ki7K9EoME2VMelGp9lOB8S9aTf4ejFmWs548IMavqvv/twFwGRyH1wBj0OFOVdL61yzyb+ihmK+u1pryeh8dmvBmJ3e90fBSn6cJzcHDdpkauGOMBw+YYAQcK16qfCvPZsxiGAiEZI2wgbErpdxQ1X1aCFpndUE1D5AVixPo3NXiHvuzhkpPzFOh9UQN9wQcn2f97FMKwNhVPt66VTl4wl3aGlq5/2tVrGQNJ8CiRuAzjXr4dEPUmOy/NlT2mVZow4KmOVcD5clv2QoUTk=

install:
  # Resolve all dependencies
  - mvn -B -V -q -DskipTests install

script:
  # Build and test with code coverage
  - mvn -B jacoco:prepare-agent test jacoco:report jacoco:report-aggregate

after_success:
  # Publish code coverage in CodeCov
  - bash <(curl -s https://codecov.io/bash)

  # Deploy snapshot in Maven central
  - bash .util/deploy_snapshot.sh

  # Publish Javadoc in Github
  - bash .util/publish_javadoc.sh
