:project-name: Commons
= Build with Maven

== Software Requirements

* https://maven.apache.org[Apache Maven] (version 3.5.0 or greater)
* Java JDK (version 11), from Oracle, OpenJDK, or Zulu

== Get the Source Code

You can download the source code of the latest release https://github.com/atlanmod/Commons/releases/latest[here] or clone the `master` branch using the following git command:

[source,bash]
----
git clone -b master --single-branch  https://github.com/atlanmod/Commons.git
----

Configure Maven's JDK to allocate more memory:

[source,bash]
----
export MAVEN_OPTS="-XX:PermSize=256m -XX:MaxPermSize=512m -XstartOnFirstThread"
----

=== Build Core Artifacts

{project-name} components are bundled as a set of `jar` files that can be imported using the Maven dependency mechanism.
You can build {project-name} components by going to the root of the source directory and run the following command:

[source,bash]
----
mvn clean install
----

Note that building the core components does not create Eclipse plugins and an local version of the update site.
To generate these additional artifacts see the next section.


== Build with an IDE

You can alternatively build {project-name} directly in Eclipse, IntelliJ, or Visual Studio Code using the Git and Maven plugins or extensions.

== Issues

If you experience issues installing or using {project-name}, you can https://github.com/atlanmod/Commons/issues[submit an issue on github] or contact us at link:mailto:&#110;e&#111;&#x65;&#x6d;&#x66;&#x40;&#103;&#x6f;&#x6f;g&#108;&#x65;&#103;r&#111;&#117;&#112;s&#46;c&#x6f;&#109;[&#110;e&#111;&#x65;&#x6d;&#x66;&#x40;&#103;&#x6f;&#x6f;g&#108;&#x65;&#103;r&#111;&#117;&#112;s&#46;c&#x6f;&#109;]

=== Known issues:

* Tests may not pass with JDK versions greater than 11.x
